version: '3.8'

services:
  postgres-ds0:
    image: postgres:15-alpine
    container_name: ch_postgres_ds0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ds_0
    ports:
      - "5432:5432"
    volumes:
      - pgdata_ds0:/var/lib/postgresql/data

  postgres-ds1:
    image: postgres:15-alpine
    container_name: ch_postgres_ds1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ds_1
    ports:
      - "5433:5432"
    volumes:
      - pgdata_ds1:/var/lib/postgresql/data

volumes:
  pgdata_ds0:
  pgdata_ds1:
