apiVersion: apps/v1
kind: Deployment
metadata:
  name: consistent-hashing-app
  labels:
    app: consistent-hashing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consistent-hashing-app
  template:
    metadata:
      labels:
        app: consistent-hashing-app
    spec:
      containers:
      - name: consistent-hashing-app
        image: consistent-hashing:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Override the database URLs to point to the Kubernetes Services
        # instead of 'localhost'
        - name: app.shards[0].url
          value: "jdbc:postgresql://postgres-ds0:5432/ds_0"
        - name: app.shards[1].url
          value: "jdbc:postgresql://postgres-ds1:5433/ds_1"
---
apiVersion: v1
kind: Service
metadata:
  name: consistent-hashing-app
spec:
  type: NodePort
  selector:
    app: consistent-hashing-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
