apiVersion: apps/v1
kind: Deployment
metadata:
  name: consistent-hashing-app
  labels:
    app: consistent-hashing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consistent-hashing-app
  template:
    metadata:
      labels:
        app: consistent-hashing-app
    spec:
      containers:
      - name: consistent-hashing-app
        image: consistent-hashing:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        # The Master Metadata DB (ds0) is the only one the app knows about on boot.
        # It uses the K8s service name `postgres-ds0` to connect.
        - name: app.master.url
          value: "jdbc:postgresql://postgres-ds0:5432/ds_0"
        - name: app.master.username
          value: "postgres"
        - name: app.master.password
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: consistent-hashing-app
spec:
  type: NodePort
  selector:
    app: consistent-hashing-app
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
